update GHA
tidymodels/modeldb pull request #33
Opened 2021-03-17 16:25 UTC by hfrick

The pkgdown workflow failed so I updated it to the latest version in our `.github` repo.

2021-03-26 01:08 UTC, topepo requested changes

2021-03-26 01:08 UTC, topepo commented on .github/workflows/pkgdown.yaml
> +          remotes::install_github("tidyverse/tidytemplate")
I think that we still need this (or is that not the case?).

2021-03-31 16:13 UTC, topepo commented on .github/workflows/pkgdown.yaml
> +          remotes::install_github("tidyverse/tidytemplate")
We'll keep it in for now.

2021-03-31 16:54 UTC, hfrick commented
@topepo I'm gonna merge based on you resolving the changes you requested originally

2021-03-31 17:46 UTC, merged